# Generated by Django 5.2.6 on 2025-09-23 15:26

import django.db.models.deletion
import sales_orders.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=20)),
                ("address", models.TextField()),
                (
                    "rut",
                    models.CharField(
                        max_length=20,
                        unique=True,
                        validators=[sales_orders.models.rut_is_valid],
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_type", models.CharField(max_length=100)),
                ("brand", models.CharField(max_length=100)),
                ("price", models.PositiveIntegerField(max_length=10)),
                ("units_per_package", models.IntegerField()),
                ("packages_per_box", models.IntegerField()),
                (
                    "promotional_discount",
                    models.PositiveIntegerField(default=0, max_length=3),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SalesOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_date", models.DateField(auto_now_add=True)),
                ("delivery_date", models.DateField()),
                ("total_amount", models.PositiveIntegerField(max_length=10)),
                (
                    "order_discount",
                    models.PositiveIntegerField(default=0, max_length=3),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("SHIPPED", "Shipped"),
                            ("DELIVERED", "Delivered"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sales_orders.client",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SalesOrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                ("unit_price", models.PositiveIntegerField(max_length=10)),
                ("unit_discount", models.PositiveIntegerField(default=0, max_length=3)),
                ("total_price", models.PositiveIntegerField(max_length=10)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sales_orders.product",
                    ),
                ),
                (
                    "sales_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sales_orders.salesorder",
                    ),
                ),
            ],
        ),
    ]
