# Generated by Django 5.2.6 on 2025-09-23 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales_orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="product",
            name="promotional_discount",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="salesorder",
            name="order_discount",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="salesorder",
            name="total_amount",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="salesorderitem",
            name="total_price",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="salesorderitem",
            name="unit_discount",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="salesorderitem",
            name="unit_price",
            field=models.PositiveIntegerField(),
        ),
    ]
