FROM mcr.microsoft.com/devcontainers/python:3.13-bullseye
WORKDIR /backend
COPY ./requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
EXPOSE 8000
# CMD ["python", "manage.py", "runserver"]